spring:
  application:
    name: config-client
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lrn-white/bookstore
          search-paths: respo
          username: lrn-white
          password: 19960614asd
      label: master

server:
  port: 8764
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
