server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-client
  cloud:
      config:
        server:
          git:
            uri: https://github.com/lrn-white/bookstore/
            search-paths: eureka-client/src/main/resources
            username: lrn-white
            password: 19960614asd
        label: master